# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 13:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('massage', models.TextField(validators=[django.core.validators.MaxLengthValidator(200)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
